# Generated by Django 3.2.13 on 2022-04-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='SKU')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('price', models.FloatField(default=0, verbose_name='price')),
                ('brand', models.CharField(blank=True, help_text='literal brand name', max_length=150, null=True, verbose_name='brand')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
